todos:
- title: Add difficulty increase option with configurable difficulty increment
  description: ""
  marked: false
  id: 0
- title: Create module to perform tests on mean fitness and parameter corr.
  description: ""
  marked: false
  id: 0
- title: Run tests on evolution algorithm
  description: ""
  marked: false
  id: 0
- title: Write paper
  description: ""
  marked: false
  id: 0
- title: Calculate phenotypic ratio (% m+/m)
  description: ""
  marked: false
  id: 0
- title: Run tests on corr. of b/d ratio and population equilibrium
  description: ""
  marked: false
  id: 0
- title: Add npyscreen form to initialize simulation?
  description: ""
  marked: false
  id: 0
